set -g mouse on
set -g history-limit 10000 

# TMUX Plugin Manager Configuration
# https://github.com/tmux-plugins/tpm

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Press Prefix + capital I to install plugins
# Press Prefix + capital U to update plugins
# Press Prefix + alt + r to restore sessions (if using tmux-resurrect)